baseURL = 'https://archive.linux.cn/'
languageCode = 'zh-Hans'
title = 'Linux.cn Archive'
theme = "mainroad"
uglyURLs = true

[Params.logo]
  title = "Linux.cn Archive"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
